version: '3'

services:
  raildb:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code/
    ports:
      - 8000:8000
    command: 'pipenv run bash -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver raildb:8000"'
    depends_on:
      - raildb_db
      - raildb_cache

  raildb_celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code/
    command: 'pipenv run celery -A raildb worker -l INFO'
    depends_on:
      - raildb

  raildb_db:
    image: postgres:latest
    volumes:
      - raildb_db_data:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./env/.env_db

  raildb_cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - raildb_cache_data:/data

volumes:
  raildb_db_data:
  raildb_cache_data:
