from django.urls import path

from home import views

app_name = 'home'


urlpatterns = [
    path(
        '',
        views.IndexView.as_view(),
        name='index'
    ),
    path(
        'signin',
        views.SigninView.as_view(),
        name='signin'
    ),
    path(
        'signup_email',
        views.SignupEmailView.as_view(),
        name='signup_email'
    ),
    path(
        'signup/<uuid:token_id>',
        views.SignupView.as_view(),
        name='signup'
    ),
    path(
        'signout',
        views.SignoutView.as_view(),
        name='signout'
    ),
    path(
        'password_reset_email',
        views.PasswordResetEmailView.as_view(),
        name='password_reset_email'
    ),
    path(
        'password_reset/<uuid:token_id>',
        views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'profile',
        views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'update_email_email',
        views.UpdateEmailEmailView.as_view(),
        name='update_email_email'
    ),
    path(
        'update_email/<uuid:token_id>',
        views.UpdateEmailView.as_view(),
        name='update_email'
    ),
    path(
        'update_display_name',
        views.UpdateDisplayNameView.as_view(),
        name='update_display_name'
    ),
    path(
        'update_password',
        views.UpdatePasswordView.as_view(),
        name='update_password'
    ),
    path(
        'delete_user',
        views.DeleteUserView.as_view(),
        name='delete_user'
    ),
    path(
        'manage_users',
        views.ManageUsersView.as_view(),
        name='manage_users'
    ),
    path(
        'update_user_staff/<uuid:user_id>',
        views.UpdateUserStaffView.as_view(),
        name='update_user_staff'
    ),
    path(
        'delete_user_staff/<uuid:user_id>',
        views.DeleteUserStaffView.as_view(),
        name='delete_user_staff'
    ),
    path(
        'manage_permissions',
        views.ManagePermissionsView.as_view(),
        name='manage_permissions'
    ),
    path(
        'register_staff',
        views.RegisterStaffView.as_view(),
        name='register_staff'
    ),
    path(
        'unregister_staff/<uuid:user_id>',
        views.UnregisterStaffView.as_view(),
        name='unregister_staff'
    ),
    path(
        'create_group',
        views.CreateGroupView.as_view(),
        name='create_group'
    ),
    path(
        'update_group/<int:group_id>',
        views.UpdateGroupView.as_view(),
        name='update_group'
    ),
    path(
        'delete_group/<int:group_id>',
        views.DeleteGroupView.as_view(),
        name='delete_group'
    ),
    path(
        'news/list',
        views.NewsListView.as_view(),
        name='news_list'
    ),
    path(
        'news/create',
        views.NewsCreateView.as_view(),
        name='news_create'
    ),
    path(
        'news/update/<uuid:pk>',
        views.NewsUpdateView.as_view(),
        name='news_update'
    ),
    path(
        'news/delete/<uuid:pk>',
        views.NewsDeleteView.as_view(),
        name='news_delete'
    ),
    path(
        'news/detail/<uuid:pk>',
        views.NewsDetailView.as_view(),
        name='news_detail'
    ),
    path(
        'json/user',
        views.JsonUser.as_view(),
        name='json_user'
    ),
]
