# Generated by Django 4.2.2 on 2023-06-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekidata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='add',
            new_name='address',
        ),
    ]
