# Generated by Django 4.2.2 on 2023-06-25 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_alter_station_freight'),
        ('ekidata', '0003_alter_company_company_name_h_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectOperator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ekidata_operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ekidata.company', verbose_name='駅データ_事業者')),
                ('library_operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library.operator', verbose_name='ライブラリ_事業者')),
            ],
            options={
                'verbose_name': 'DB連携_事業者',
                'verbose_name_plural': 'DB連携_事業者',
                'ordering': ['library_operator'],
            },
        ),
    ]
