# Generated by Django 4.2.2 on 2023-06-27 15:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_alter_station_freight'),
        ('ekidata', '0006_alter_connectstation_library_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectStationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ekidata_station_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekidata.stationgroup', verbose_name='駅データ_駅グループ')),
                ('library_station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library.station', verbose_name='ライブラリ_駅')),
            ],
            options={
                'verbose_name': 'DB連携_駅グループ',
                'verbose_name_plural': 'DB連携_駅グループ',
                'ordering': ['library_station'],
            },
        ),
        migrations.DeleteModel(
            name='ConnectStation',
        ),
    ]
