# Generated by Django 4.2.2 on 2023-06-29 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekidata', '0009_alter_connectstation_library_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectstation',
            options={'ordering': ['library_station', 'ekidata_station'], 'verbose_name': 'DB連携_駅', 'verbose_name_plural': 'DB連携_駅'},
        ),
    ]
