# Generated by Django 4.2.3 on 2023-07-09 12:08

from django.db import migrations, models
import raildb.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ekidata', '0010_alter_connectstation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name_k',
            field=models.CharField(blank=True, max_length=80, null=True, validators=[raildb.validators.KatakanaRegexValidator], verbose_name='駅名称（カナ）'),
        ),
    ]
