# Generated by Django 4.2.3 on 2023-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekidata', '0011_alter_station_station_name_k'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_g_cd',
            field=models.IntegerField(default=1, verbose_name='駅グループコード'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StationGroup',
        ),
    ]
