# Generated by Django 4.1.2 on 2022-10-09 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import home.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='例：tokino_sora@hololive.com', max_length=254, unique=True, verbose_name='Eメールアドレス')),
                ('display_name', models.CharField(help_text='例：そらちゃん', max_length=50, verbose_name='表示名')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ権限')),
                ('is_active', models.BooleanField(default=True, help_text='無効にするとログインできなくなります', verbose_name='有効')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'ordering': ['-is_superuser', '-is_staff'],
                'permissions': [('raildb_manage_user', 'ユーザー管理')],
            },
            managers=[
                ('objects', home.models.RailDBUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('important', '重要'), ('update', '更新情報'), ('ordinary', 'お知らせ')], max_length=10, verbose_name='種別')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-update_datetime'],
                'permissions': [('raildb_manage_news', 'お知らせ管理')],
            },
        ),
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Eメールアドレス')),
                ('kind', models.CharField(choices=[('signup', 'アカウント新規登録'), ('password_reset', 'パスワード再設定'), ('email_update', 'Eメールアドレス変更')], max_length=20, verbose_name='種別')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_used', models.BooleanField(default=False, verbose_name='使用済み')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー')),
            ],
            options={
                'verbose_name': 'Eメールトークン',
                'verbose_name_plural': 'Eメールトークン',
            },
        ),
    ]
