# Generated by Django 4.1.2 on 2022-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_display_name_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(help_text='例：そらちゃん', max_length=50, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='例：tokino_sora@hololive.com', max_length=254, unique=True, verbose_name='Eメールアドレス'),
        ),
    ]
