# Generated by Django 4.1.2 on 2022-10-07 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_emailtoken_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成ユーザー'),
        ),
    ]
