# Generated by Django 4.1.2 on 2022-10-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_emailtoken_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtoken',
            old_name='created_by',
            new_name='created_user',
        ),
    ]
