# Generated by Django 4.1.2 on 2022-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_created_by_emailtoken_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='kind',
            field=models.CharField(choices=[('signup', 'アカウント新規登録'), ('password_reset', 'パスワード再設定'), ('email_update', 'Eメールアドレス変更')], max_length=20, verbose_name='種別'),
        ),
    ]
