# Generated by Django 4.1.2 on 2022-10-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_emailtoken_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', '全てのユーザー情報を管理できます')], 'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
    ]
