# Generated by Django 4.1.2 on 2022-10-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manage_users', 'ユーザー管理')], 'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
    ]
