# Generated by Django 4.1.2 on 2022-10-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_superuser', '-is_staff'], 'permissions': [('raildb_manage_users', 'ユーザー管理')], 'verbose_name': 'ユーザー', 'verbose_name_plural': 'ユーザー'},
        ),
    ]
