# Generated by Django 4.1.2 on 2022-10-09 13:52

from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', home.models.RailDBUserManager()),
            ],
        ),
    ]
