# Generated by Django 4.1.2 on 2022-10-09 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('important', '重要'), ('update', '更新情報'), ('ordinary', 'お知らせ')], max_length=10, verbose_name='種別')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-update_datetime'],
                'permissions': [('raildb_manage_news', 'お知らせ管理')],
            },
        ),
    ]
